import * as THREE from 'three';
export class MissionDirector {
  constructor({events,player,enemies,world,effects,audio}){Object.assign(this,{events,player,enemies,world,effects,audio});this.operation=null;this.actIndex=0;this.progress=0;this.complete=false;this.marker=null;this.defenseTimer=0;this.interact=0;this.kills=0;events.on('enemy:killed',()=>this.onKill());}
  start(op){this.operation=op;this.actIndex=0;this.progress=0;this.complete=false;this.kills=0;this.beginAct();}
  get act(){return this.operation?.acts[this.actIndex];}
  beginAct(){this.progress=0;this.interact=0;if(this.marker)this.world.removeMarker(this.marker);const act=this.act;if(!act)return this.finish();this.marker=this.world.createObjectiveMarker(this.world.objectivePoint(this.actIndex),act.type);if(act.type==='defense')this.defenseTimer=act.amount;if(act.type==='hunt')this.enemies.spawnBoss();this.events.emit('mission:act',{act,index:this.actIndex,total:this.operation.acts.length});}
  update(dt){if(this.complete||!this.act)return;const d=this.player.position.distanceTo(this.marker.position);if(this.act.type==='uplink'||this.act.type==='extraction'){if(d<2.3)this.advance();}else if(this.act.type==='sabotage'){if(d<2.8){this.interact+=dt;this.events.emit('interaction',{text:`HOLD POSITION · ${Math.floor(this.interact/3*100)}%`});if(this.interact>=3){this.progress++;this.interact=0;this.marker.position.copy(this.world.objectivePoint(this.actIndex+this.progress*2));if(this.progress>=this.act.amount)this.advance();}}}else if(this.act.type==='defense'){if(d<10){this.defenseTimer-=dt;this.progress=this.act.amount-this.defenseTimer;if(this.defenseTimer<=0)this.advance();}}else if(this.act.type==='containment'){if(d<3){this.interact+=dt;this.events.emit('interaction',{text:`ARM CONTAINMENT DEVICE · ${Math.min(100,Math.floor(this.interact/6*100))}%`});if(this.interact>=6){this.events.emit('cinematic:detonation',{position:this.marker.position.clone()});setTimeout(()=>this.advance(),5500);this.interact=-999;}}}else if(this.act.type==='endless'){this.progress=this.kills;}}
  onKill(){this.kills++;if(!this.act)return;if(this.act.type==='eliminate'&&++this.progress>=this.act.amount)this.advance();if(this.act.type==='hunt'&&this.kills>0)this.advance();}
  advance(){this.actIndex++;this.beginAct();}
  finish(){this.complete=true;if(this.marker)this.world.removeMarker(this.marker);this.events.emit('mission:complete',{operation:this.operation});}
}
