export class HUD {
  constructor({events,player,weapon,abilities,missions,profile}){Object.assign(this,{events,player,weapon,abilities,missions,profile});this.el={health:q('health'),armor:q('armor'),healthFill:q('health-fill'),armorFill:q('armor-fill'),ammo:q('ammo'),reserve:q('reserve'),weapon:q('weapon-name'),ability:q('ability-name'),abilityState:q('ability-state'),mission:q('mission-name'),objectives:q('objectives'),op:q('operation-label'),className:q('class-name'),rank:q('rank-label'),prompt:q('interaction-prompt'),subtitle:q('subtitle')};this.promptTimer=0;events.on('mission:act',p=>this.act(p));events.on('interaction',p=>{this.el.prompt.textContent=p.text;this.el.prompt.hidden=false;this.promptTimer=.2;});events.on('player:damage',()=>{q('damage-vignette').classList.add('hit');setTimeout(()=>q('damage-vignette').classList.remove('hit'),90);});}
  enter(op,classDef){q('menu').classList.remove('show');this.el.mission.textContent=op.name.toUpperCase();this.el.op.textContent=`OPERATION ${String(op.index).padStart(2,'0')} // ${op.biome.toUpperCase()}`;this.el.className.textContent=classDef.name.toUpperCase();this.el.rank.textContent=`RANK ${this.profile.rank}`;this.el.ability.textContent=classDef.ability.toUpperCase();}
  act({act,index,total}){this.el.objectives.innerHTML=`<div class="objective active"><i></i><span>${act.label}</span><b>${index+1}/${total}</b></div>`;}
  update(dt){this.el.health.textContent=Math.ceil(this.player.health);this.el.armor.textContent=Math.ceil(this.player.armor);this.el.healthFill.style.width=`${Math.max(0,this.player.health/this.player.maxHealth*100)}%`;this.el.armorFill.style.width=`${Math.max(0,this.player.armor/this.player.maxArmor*100)}%`;if(this.weapon.definition){this.el.ammo.textContent=this.weapon.mag;this.el.reserve.textContent=this.weapon.reserve;this.el.weapon.textContent=this.weapon.definition.name.toUpperCase();}this.el.abilityState.textContent=this.abilities.ready?'READY':`${this.abilities.cooldown.toFixed(1)}s`;this.promptTimer-=dt;if(this.promptTimer<=0)this.el.prompt.hidden=true;}
  kill(name){const d=document.createElement('div');d.textContent=`✦ ${name} ELIMINATED`;q('killfeed').prepend(d);setTimeout(()=>d.remove(),2400);}
  showPause(){q('pause-menu').classList.add('show');} hidePause(){q('pause-menu').classList.remove('show');} onResume(fn){q('resume-button').onclick=()=>{this.hidePause();fn();};} onReturn(fn){q('return-button').onclick=fn;} showComplete(op,score,kills,xp,loss=false){q('complete-title').textContent=loss?'COMBAT LOSS':op.name;q('retry-button').style.display=loss?'inline-flex':'none';q('complete-stats').innerHTML=`SCORE <b>${score}</b> · ELIMINATIONS <b>${kills}</b> · XP <b>${xp}</b>`;q('mission-complete').classList.add('show');q('continue-button').onclick=()=>location.reload();}
}
const q=id=>document.getElementById(id);
