import * as THREE from 'three';
export class AbilitySystem {
  constructor({ scene,input,player,weapon,enemies,effects,events,audio }) { Object.assign(this,{scene,input,player,weapon,enemies,effects,events,audio}); this.classDef=null; this.cooldown=0; this.active=0; this.objects=[]; }
  configure(def){ this.classDef=def; this.cooldown=0; this.active=0; this.clear(); }
  clear(){for(const o of this.objects)this.scene.remove(o);this.objects=[];this.active=0;if(this.player){this.player.damageMultiplier=1;this.player.speedMultiplier=1;}if(this.weapon){this.weapon.fireRateMultiplier=1;this.weapon.critMultiplier=1;}}
  update(dt){ if(!this.classDef)return; this.cooldown=Math.max(0,this.cooldown-dt); this.active=Math.max(0,this.active-dt); if(this.input.wasPressed('KeyQ')&&this.cooldown<=0)this.activate(); if(this.active<=0){ this.player.damageMultiplier=1; this.weapon.fireRateMultiplier=1; this.player.speedMultiplier=1; this.weapon.critMultiplier=1; } this.updateObjects(dt); }
  activate(){ this.cooldown=this.classDef.cooldown; this.audio.ability(); const id=this.classDef.id; if(id==='vanguard'){this.active=9;this.player.speedMultiplier=1.35;this.weapon.fireRateMultiplier=1.35;} else if(id==='bulwark'){this.active=11;this.player.armor=Math.min(this.player.maxArmor+90,this.player.armor+90);this.player.damageMultiplier=.45;} else if(id==='trapper')this.deployMines(); else if(id==='engineer')this.deployTurret(); else if(id==='spectre'){this.active=10;this.weapon.critMultiplier=2.15;this.enemies.reveal(10);} else if(id==='lifeline'){this.active=9;this.player.heal(55);this.player.armor=Math.min(this.player.maxArmor,this.player.armor+50);} this.events.emit('ability:used',{def:this.classDef}); }
  deployMines(){ const f=new THREE.Vector3(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),this.player.yaw); for(let i=-2;i<=2;i++){const m=new THREE.Mesh(new THREE.CylinderGeometry(.22,.32,.12,10),new THREE.MeshBasicMaterial({color:0xbaff43}));m.position.copy(this.player.position).add(f.clone().multiplyScalar(4+Math.abs(i)*1.2));m.position.x+=i*1.3;m.position.y=.08;m.userData={type:'mine',life:30};this.scene.add(m);this.objects.push(m);} }
  deployTurret(){ const g=new THREE.Group(); const base=new THREE.Mesh(new THREE.CylinderGeometry(.5,.65,.5,10),new THREE.MeshStandardMaterial({color:0x33424b,metalness:.8,roughness:.35})); const head=new THREE.Mesh(new THREE.BoxGeometry(.75,.35,.8),new THREE.MeshStandardMaterial({color:0x4b5a65,metalness:.75}));head.position.y=.55;g.add(base,head);g.position.copy(this.player.position);g.position.y=.25;g.userData={type:'turret',life:36,cool:0};this.scene.add(g);this.objects.push(g); }
  updateObjects(dt){ for(let i=this.objects.length-1;i>=0;i--){const o=this.objects[i];o.userData.life-=dt;if(o.userData.type==='mine'){const target=this.enemies.nearest(o.position,2.4);if(target){this.effects.explosion(o.position,0x9dff43);this.enemies.radialDamage(o.position,5,160);o.userData.life=0;}}else{o.userData.cool-=dt;const target=this.enemies.nearest(o.position,24);if(target){o.lookAt(target.position.x,o.position.y,target.position.z);if(o.userData.cool<=0){o.userData.cool=.16;this.enemies.damage(target,13,false);this.effects.tracer(o.position.clone().add(new THREE.Vector3(0,.65,0)),target.position.clone().add(new THREE.Vector3(0,1.3,0)),0x63e8ff);}}}if(o.userData.life<=0){this.scene.remove(o);this.objects.splice(i,1);}} }
  get ready(){return this.cooldown<=0} get cooldownRatio(){return this.classDef?this.cooldown/this.classDef.cooldown:0}
}
