import * as THREE from 'three';
import { damp } from '../core/math.js';
export class Player {
  constructor({camera,input,world,events}){Object.assign(this,{camera,input,world,events});this.position=new THREE.Vector3();this.velocity=new THREE.Vector3();this.yaw=0;this.pitch=0;this.health=100;this.armor=100;this.maxHealth=100;this.maxArmor=100;this.vertical=0;this.grounded=true;this.eye=1.72;this.speedMultiplier=1;this.damageMultiplier=1;this.bob=0;this.stepTimer=0;this.slide=0;this.configure({health:110,armor:80,speed:1});}
  configure(def){this.classDef=def;this.maxHealth=def.health;this.maxArmor=def.armor;this.health=this.maxHealth;this.armor=this.maxArmor;this.position.set(0,0,20);this.velocity.set(0,0,0);this.yaw=Math.PI;this.pitch=0;this.vertical=0;this.grounded=true;this.slide=0;this.speedMultiplier=1;this.damageMultiplier=1;}
  update(dt){const look=this.input.consumeLook();this.yaw-=look.x*.0019;this.pitch=Math.max(-1.45,Math.min(1.45,this.pitch-look.y*.0019));let f=(this.input.down('KeyW')?1:0)-(this.input.down('KeyS')?1:0),s=(this.input.down('KeyD')?1:0)-(this.input.down('KeyA')?1:0);const l=Math.hypot(f,s)||1;f/=l;s/=l;const crouch=this.input.down('ControlLeft'),sprint=this.input.down('ShiftLeft')&&f>.2&&!crouch;const forward=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)),right=new THREE.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw));const wish=forward.multiplyScalar(f).add(right.multiplyScalar(s));if(wish.lengthSq())wish.normalize();if(this.input.wasPressed('ControlLeft')&&this.grounded&&this.velocity.length()>6){this.slide=.75;}let speed=(crouch?3.3:sprint?9.4:6.0)*this.classDef.speed*this.speedMultiplier;if(this.slide>0){this.slide-=dt;speed=11.5*(.65+.35*Math.max(0,this.slide/.75));}const target=wish.multiplyScalar(speed);this.velocity.x=damp(this.velocity.x,target.x,15,dt);this.velocity.z=damp(this.velocity.z,target.z,15,dt);this.world.moveObject({position:this.position},new THREE.Vector3(this.velocity.x*dt,0,this.velocity.z*dt),.43);if(this.grounded&&this.input.wasPressed('Space')){this.vertical=7.1;this.grounded=false;}this.vertical-=20.5*dt;this.position.y+=this.vertical*dt;if(this.position.y<=0){this.position.y=0;this.vertical=0;this.grounded=true;}const moving=Math.hypot(this.velocity.x,this.velocity.z)>.4;if(moving&&this.grounded){this.bob+=dt*(sprint?13:9.5);this.stepTimer-=dt;if(this.stepTimer<=0){this.stepTimer=sprint?.28:.4;this.events.emit('player:step');}}this.eye=damp(this.eye,crouch||this.slide>0?1.18:1.72,12,dt);const bob=moving&&this.grounded?Math.sin(this.bob*2)*.025:0;this.camera.position.set(this.position.x,this.position.y+this.eye+bob,this.position.z);this.camera.rotation.y=this.yaw;this.camera.rotation.x=this.pitch;}
  damage(amount){amount*=this.damageMultiplier;const absorbed=Math.min(this.armor,amount*.7);this.armor-=absorbed;this.health-=amount-absorbed;this.events.emit('player:damage',{health:this.health,armor:this.armor});if(this.health<=0){this.health=0;this.events.emit('player:dead');}}
  heal(v){this.health=Math.min(this.maxHealth,this.health+v);}
}
