import * as THREE from 'three';
import { WEAPONS } from '../data/weapons.js';
import { createWeaponModel } from '../models/weapon.js';
import { damp } from '../core/math.js';
export class WeaponSystem {
  constructor({camera,input,player,enemies,effects,audio,events}){Object.assign(this,{camera,input,player,enemies,effects,audio,events});this.group=new THREE.Group();camera.add(this.group);this.ray=new THREE.Raycaster();this.fireClock=0;this.reloading=0;this.aim=0;this.fireRateMultiplier=1;this.critMultiplier=1;}
  configure(classDef){this.definition=WEAPONS[classDef.weapon];this.mag=this.definition.mag;this.reserve=this.definition.reserve;this.fireClock=0;this.reloading=0;this.group.clear();this.group.add(createWeaponModel(this.definition.id,classDef.color));}
  update(dt){if(!this.definition)return;this.fireClock=Math.max(0,this.fireClock-dt);if(this.reloading>0){this.reloading-=dt;if(this.reloading<=0)this.finishReload();}const ads=this.input.button(2)&&this.reloading<=0;this.aim=damp(this.aim,ads?1:0,15,dt);this.camera.fov=damp(this.camera.fov,ads?54:76,15,dt);this.camera.updateProjectionMatrix();const moving=Math.hypot(this.player.velocity.x,this.player.velocity.z);const t=performance.now()*.001;this.group.position.set(damp(this.group.position.x,ads?0:.34,14,dt),damp(this.group.position.y,ads?-.21:-.34,14,dt)+Math.sin(t*9)*.004*moving,damp(this.group.position.z,ads?-.62:-.78,14,dt));this.group.rotation.z=damp(this.group.rotation.z,Math.sin(t*5)*.008*moving,8,dt);if(this.input.wasPressed('KeyR'))this.reload();const wants=this.input.button(0);if(wants&&(this.definition.automatic||this.fireClock<=0))this.tryFire();}
  tryFire(){if(this.fireClock>0||this.reloading>0)return;if(this.mag<=0){this.reload();return;}this.mag--;this.fireClock=1/(this.definition.fireRate*this.fireRateMultiplier);const spread=(this.aim>.7?this.definition.adsSpread:this.definition.spread)*(1+Math.hypot(this.player.velocity.x,this.player.velocity.z)*.05);const dir=new THREE.Vector3(0,0,-1).applyQuaternion(this.camera.quaternion);dir.x+=(Math.random()-.5)*spread;dir.y+=(Math.random()-.5)*spread;dir.z+=(Math.random()-.5)*spread;dir.normalize();this.ray.set(this.camera.position,dir);this.ray.far=this.definition.range;const hit=this.enemies.raycast(this.ray);const end=hit?hit.point:this.camera.position.clone().add(dir.multiplyScalar(this.definition.range));this.effects.tracer(this.camera.position.clone().add(dir.clone().multiplyScalar(.8)),end,0x8edfff);if(hit){const mult=hit.critical?2.0*this.critMultiplier:1;this.enemies.damage(hit.enemy,this.definition.damage*mult,hit.critical);this.effects.burst(hit.point,hit.critical?0x7ddcff:0xff5a42,hit.critical?18:8);}this.player.pitch=Math.max(-1.45,this.player.pitch-this.definition.recoil*(.6+Math.random()*.55));this.player.yaw+=(Math.random()-.5)*this.definition.recoil*.45;this.audio.shot();this.events.emit('weapon:fired',{hit});}
  reload(){if(this.reloading>0||this.mag>=this.definition.mag||this.reserve<=0)return;this.reloading=this.definition.reload/(this.fireRateMultiplier>1?1.2:1);this.audio.reload();}
  finishReload(){const n=Math.min(this.definition.mag-this.mag,this.reserve);this.mag+=n;this.reserve-=n;}
}
